GET https://api.github.com/users/guilhermesantoss HTTP/1.1

###

# Criar uma aula
POST http://localhost:3333/classes HTTP/1.1
content-type: application/json

{
  "name": "Guilherme Santos",
  "avatar": "https://avatars3.githubusercontent.com/u/16351117?s=460&u=157575a4f7bc20221f4693aa045fd800654c7016&v=4",
  "whatsapp": "5511956564143",
  "bio": "Trabalho como Front-End Developer desde 2012, onde comecei a minha aventura no mundo da Programação Web.",
  "subject": "Matemática",
  "cost": 60,
  "schedule": [
    { "week_day": 1, "from": "8:00", "to": "12:00" },
    { "week_day": 3, "from": "13:00", "to": "18:00" },
    { "week_day": 4, "from": "8:00", "to": "12:00" }
  ]
}

###

# Listar aulas
GET http://localhost:3333/classes
    ?week_day=1
    &subject=Matemática
    &time=9:00

###